DROP TABLE IF EXISTS BookRecipe;
DROP TABLE IF EXISTS Book;

CREATE TABLE Book (
	BookId UNIQUEIDENTIFIER NOT NULL,

	Token BINARY(40) NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,

	CONSTRAINT PK_Book
		PRIMARY KEY (BookId)
);

CREATE TABLE BookRecipe (
	BookId UNIQUEIDENTIFIER NOT NULL,
	RecipeId UNIQUEIDENTIFIER NOT NULL,

	[Name] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	Servings INT NOT NULL,
	AddedAt DATETIME NOT NULL,
	LastModifiedAt DATETIME NOT NULL,

	CONSTRAINT PK_BookRecipe
		PRIMARY KEY (BookId, RecipeId),
	CONSTRAINT FK_BookRecipe_Book
		FOREIGN KEY (BookId)
		REFERENCES Book (BookId)
		ON DELETE CASCADE
);